name: Tests
on:
  push:
    branches: [ main ]
  pull_request:

env:
  POETRY_VERSION: 1.5.1

jobs:
  int:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests - Redis cluster
        run: |
          docker network create --subnet=172.28.0.0/24 test_network
          export REDIS_PASSWORD=test1234
          export NETWORK_NAME=test_network
          docker-compose -f ./int/docker-compose.yml run tests-cluster
      - name: Run integration tests - Redis host
        run: |
          export REDIS_PASSWORD=test1234
          export NETWORK_NAME=test_network
          docker-compose -f ./int/docker-compose.yml run tests-host
      - name: Print logs on failure
        if: failure()
        run: |
          docker ps -a
          docker-compose -f ./int/docker-compose.yml logs
      - name: Clean up integration tests
        if: always()
        run: |
          docker-compose -f ./int/docker-compose.yml down
