name: Tests
on:
  push:
    branches: [ main ]
  pull_request:

env:
  POETRY_VERSION: 1.1.7

jobs:
  int:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run integration tests
      run: |
        docker-compose -f ./int/docker-compose.yml run tests
    - name: Print logs on failure
      if: failure()
      run: |
        docker-compose -f ./int/docker-compose.yml logs
    - name: Clean up integration tests
      if: always()
      run: |
        docker-compose -f ./int/docker-compose.yml down
